version: '2'
services:
  proxy:
    build: ./
    environment:
      DEFAULT_HOST: "Default Domain ex: bar.com"
      DEFAULT_EMAIL: "Default Email ex: foo@bar.com"
      UPSTREAM_HOST: localhost
      UPSTREAM_PORT: 3000
    stdin_open: true
    volumes:
    - ./local/nginx/htpasswd:/etc/nginx/htpasswd
    - ./local/nginx/vhost.d:/etc/nginx/vhost.d
    - ./local/nginx/letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
