name: Rancher Active Proxy
description: "Automatic Active Proxy for Rancher with Let's Encrypt support"
version: "v0.0.2"
category: Proxy
maintainer: RaymondBenc
license: MIT
projectURl: "https://github.com/SocialEngine/rancher-active-proxy"
